language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

git:
  depth: 1

notifications:
  email: false

before_install:
  - export TZ=Europe/Moscow

script:
  - make ci

before_deploy:
  - make pack
  - sha256sum *.tgz > sha256sums.txt

deploy:
  provider: releases
  api_key: e41cfa7ab0921dd6020f9377390ae9c53422f611
  file:
    - tinfo-${TRAVIS_TAG}-darwin-amd64.tgz
    - tinfo-${TRAVIS_TAG}-linux-amd64.tgz
    - tinfo-${TRAVIS_TAG}-windows-amd64.tgz
    - sha256sums.txt
  skip_cleanup: true
  overwrite: true
  on:
    repo: vutenkov/tinfo
    tags: true
