language: go

env:
  - GO111MODULE=on TZ=Europe/Moscow GOLANGCI_LINT_VERSION=v1.15.0

go:
  - 1.11.x

git:
  depth: 1

notifications:
  email: false

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

script:
  - make ci

before_deploy:
  - make pack
  - sha256sum *.tgz > sha256sums.txt

deploy:
  provider: releases
  api_key:
    secure: "APPuiFSRuPsTFTFC7IO0TVyOTEqehNVMAIChH8iWgkMYtb4h1w4Mka/vezIvjSDh25fNUkc9Zww26FLvK7iLusXuB0TtBfN5MFk+LpsqbAf0M3gbbmkXINSzK8oAMBnCm4Eoq10lKWKPWteLMD1FKcKejNZkd46/6GIYthcT8t77r373Fo73ArgBdnC9gBVX79aOMpsomhsQCvs/apr00zRAdbLLyjdvCAQYtoo81qw5+TOByexXZxBU72yK6W45mhWNBHsMaWq0I123LmbU49tUaUvwEA5tE4CczWsN2FurjqERHjLecgEL26z/51vY8CK8z4L3UWpNZfI0oMO3403TWVYZUWhyswABC0/fyOOg4jCkkXksnzqxzHrft16BdrMloitltklgxQvZ7DBTvd5XJU2s7G/zKAbdeoQkpUCrIbmmeMUipgnJM7p/lQPQcdiEnM4KIHAKsmgwpmMh4e5ZlFepWo/GoG5SdpvggX/QK7YUMSJX3GdVOaf9xwL2A1fsQbQSuOypO5+k0Dr+313i/W8SrmwXWm8utiIJoYzVP2MfQdcA/G666pnbDLNRFRYDfnr2WidBCPIzwvMw7+F1i7eES0Zuc5llIM6CWOjLvYXDQQj1ukJGiAb4mqcei8F50vAci7PYM6tRYiEojyBp9m7U+omgXiDo3uyHlGE="
  file:
    - tinfo-${TRAVIS_TAG}-darwin-amd64.tgz
    - tinfo-${TRAVIS_TAG}-linux-amd64.tgz
    - tinfo-${TRAVIS_TAG}-windows-amd64.tgz
    - sha256sums.txt
  skip_cleanup: true
  overwrite: true
  on:
    repo: vutenkov/tinfo
    tags: true
