language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

git:
  depth: 1

notifications:
  email: false

before_install:
  - export TZ=Europe/Moscow

script:
  - make ci

before_deploy:
  - make pack
  - sha256sum *.tgz > sha256sums.txt

deploy:
  provider: releases
  api_key:
    secure: Nl0J31t5abKu2ib1wgn5Fni5DmSMZXQxRFZcwtP1rNfNDs7jbfy2z51ERYIBVCYXhJuDY5T7jOPioJogwpV4m1RMd3bYgA0G5OQv4fXhTaqShyGr6R5oOiEwXdSQ0N9Vo5ex3cyvUh/v6rDzq2HNsVWG3CIpDNWKD+eErQ1aJCB81ztyhK/XGE9UcdENDq/QlHEKQJYMe+Df0/+DArX/8f2ytGh22f2CF1vCEU4M1tVcQpnUpB4c6E5cNY8HcCHRatyQj1Oisv220B0YWkmh8U3QLcI6sah5CZ+pPbhS7iBFZHqU5rYi1NNDRQdMO3aXnQLyRl9aJVLh7ff9wcQpp1k6YqZ+5GC9Bt70tBMzEU8eafSwNNjIhd77cozjD5533thgGsyxytRviMc4MNJ5kkdawsC53btHjQdIGFHQ0RcneuOoAP3tm8tuiNwjcNaKXYMqATPKkm6aHVzmSmHy3BrJ9Xi9iq4KdSB9XA2VNtckUEXyMFwXpmmfhnmXqtTxm57WylhErGPo9Td4EpAxtGLNXmYLZbrbv9as/dzhV76NGid3vkgBV65gZPvXGyBYcOVB12mCjrpmi7KrOhZ60imavVuyFIZqu1lVT1LEkCTs5qM6mJ+eW4stoZOn6HNXUiKj0ZTf5gt0tHS6DyGeN0RuJ0nU/6WO4+OSEbJ7k2c=
  file:
    - tinfo-${TRAVIS_TAG}-darwin-amd64.tgz
    - tinfo-${TRAVIS_TAG}-linux-amd64.tgz
    - tinfo-${TRAVIS_TAG}-windows-amd64.tgz
    - sha256sums.txt
  skip_cleanup: true
  overwrite: true
  on:
    repo: vutenkov/tinfo
    tags: true
